### ISSUE TITLE
Newer source code version

### ISSUE THREAD

**Issue by Poussinou** [LibreGamesArchive/monster-rpg-2#1]
Hi,

It looks like we have a newer version of this source code here: https://github.com/kraekin/monster-rpg-2

Could you please sync your repo with this one. I'll then use your repo as a reference for my list of FLOSS games on steam that you can find [here](https://github.com/Poussinou/FLOSS-Games-on-Steam)

**Comment by akien-mga** [comment]
Sorry for the delay. I synced with that repo now.
